"Tanggal Output"
"Tanggal Pembelian"
"Tahun"
"Harga Perolehan"
"PPN"
"Biaya Lain-Lain"
"Total Harga Perolehan"
"BAST Output"
"BAST"
"Kondisi"
"Insurance"
"User"
"Jabatan"
"Initisal"
"Kode Wilayah"
"Kode Asset"
"Tahun Pembelian"
"Kode Urut barang"
"Penyusutan Perbulan"
"Total Bulan Penyusutan"
"Total Penyusutan"
"Nomor Resi"
"Tipe"