export const OverviewColumn = [
	'Action', 
    'Purchase Date',                 
	'Purchase Date Input',            
	'Year',                     
	'PO Number',                 
	'Vendor Name',                   
	'Item Name',                     
	'Acquisition Cost',             
	'PPN',                         
	'Additional Cost',              
	'Total Acquisition Cost',       
	'Asset Category Subproduct Name', 
	'Asset Category',
	'BAST',
    'BAST Input',
	'Condition',                   
	'Insurance',                   
	'Location',                    
	'User',                        
	'Position',                    
	'Initial',                    
	'Location ID',                  
	'Product Code',                 
	'Purchase Year',                
	'Item Order Code',             
	'Asset Number',                 
	'UsefulLife',                 
	'Monthly Depreciation',          
	'Depreciation Month',           
	'Total Depreciation',            
	'Current Asset Value',
]